# These are supported funding model platforms

github: # Replace with your GitHub username
ko_fi: # Replace with your Ko-fi page name
custom: ['https://buymeacoffee.com/yourpage'] # Replace with your Buy Me a Coffee link
