/**
 * ATS Score Service
 * Analyzes CV data and returns an ATS compatibility score with actionable suggestions
 */

class ATSScoreService {
  constructor() {
    // Common ATS keywords by category for density check
    this.commonKeywords = {
      tech: ['javascript', 'python', 'react', 'node', 'sql', 'aws', 'docker', 'api', 'git', 'agile', 'ci/cd', 'kubernetes', 'typescript', 'rest', 'microservices', 'cloud', 'linux', 'database', 'testing', 'devops'],
      marketing: ['seo', 'analytics', 'content', 'campaign', 'social media', 'brand', 'conversion', 'roi', 'kpi', 'strategy', 'email', 'funnel', 'growth', 'audience', 'engagement'],
      sales: ['revenue', 'quota', 'pipeline', 'closing', 'negotiation', 'crm', 'forecast', 'territory', 'acquisition', 'retention', 'upsell', 'business development', 'account management'],
      finance: ['financial', 'audit', 'budget', 'forecast', 'compliance', 'reporting', 'analysis', 'risk', 'gaap', 'reconciliation', 'variance', 'accounting'],
      hr: ['recruitment', 'onboarding', 'retention', 'compliance', 'performance', 'training', 'benefits', 'payroll', 'employee relations', 'hris'],
      general: ['management', 'leadership', 'project', 'strategy', 'communication', 'collaboration', 'results', 'improvement', 'development', 'implementation', 'optimization', 'coordination']
    };
  }

  /**
   * Calculate ATS score for given CV data
   * @param {Object} data - CV data object
   * @returns {Object} Score result with breakdown and suggestions
   */
  calculate(data) {
    const checks = [];
    const suggestions = [];

    // 1. Contact Info Completeness (15 pts)
    const contactCheck = this._checkContactInfo(data.personalInfo || {});
    checks.push(contactCheck);

    // 2. Professional Summary (15 pts)
    const summaryCheck = this._checkSummary(data.summary || '');
    checks.push(summaryCheck);

    // 3. Keyword Density (15 pts)
    const keywordCheck = this._checkKeywords(data);
    checks.push(keywordCheck);

    // 4. Experience Bullet Points (20 pts)
    const experienceCheck = this._checkExperience(data.experience || []);
    checks.push(experienceCheck);

    // 5. Skills Format (15 pts)
    const skillsCheck = this._checkSkills(data.skills || []);
    checks.push(skillsCheck);

    // 6. Education Completeness (10 pts)
    const educationCheck = this._checkEducation(data.education || []);
    checks.push(educationCheck);

    // 7. File Format / Structure (10 pts) — always full if using our tool
    const formatCheck = {
      name: 'File Format & Structure',
      score: 10,
      maxScore: 10,
      passed: true,
      details: 'ATS-friendly format generated by CVForge'
    };
    checks.push(formatCheck);

    // Aggregate
    const totalScore = checks.reduce((sum, c) => sum + c.score, 0);
    const maxScore = checks.reduce((sum, c) => sum + c.maxScore, 0);
    const overallScore = Math.round((totalScore / maxScore) * 100);

    // Collect suggestions
    checks.forEach(c => {
      if (c.suggestions) {
        suggestions.push(...c.suggestions);
      }
    });

    return {
      overallScore,
      maxPossible: 100,
      grade: this._getGrade(overallScore),
      checks,
      suggestions,
      summary: this._getSummary(overallScore)
    };
  }

  _checkContactInfo(info) {
    let score = 0;
    const maxScore = 15;
    const suggestions = [];
    const fields = [
      { key: 'fullName', label: 'Full Name', pts: 3 },
      { key: 'email', label: 'Email', pts: 3 },
      { key: 'phone', label: 'Phone', pts: 2 },
      { key: 'location', label: 'Location', pts: 2 },
      { key: 'jobTitle', label: 'Job Title', pts: 3 },
      { key: 'linkedin', label: 'LinkedIn/Website', pts: 2 }
    ];

    const missing = [];
    fields.forEach(f => {
      if (info[f.key] && String(info[f.key]).trim().length > 0) {
        score += f.pts;
      } else {
        missing.push(f.label);
      }
    });

    // Email format check
    if (info.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(info.email)) {
      score -= 1;
      suggestions.push('Email format appears invalid — ATS may not be able to contact you');
    }

    if (missing.length > 0) {
      suggestions.push(`Add missing contact info: ${missing.join(', ')}`);
    }

    return {
      name: 'Contact Information',
      score: Math.max(0, score),
      maxScore,
      passed: score >= 10,
      details: missing.length === 0 ? 'All contact fields present' : `Missing: ${missing.join(', ')}`,
      suggestions
    };
  }

  _checkSummary(summary) {
    let score = 0;
    const maxScore = 15;
    const suggestions = [];
    const len = summary.trim().length;

    if (len === 0) {
      score = 0;
      suggestions.push('Add a professional summary — it\'s the first thing ATS and recruiters read');
      suggestions.push('Aim for 3-5 sentences (150-400 characters)');
    } else if (len < 50) {
      score = 3;
      suggestions.push('Your summary is too short — expand it to 3-5 sentences for better ATS visibility');
    } else if (len < 150) {
      score = 8;
      suggestions.push('Summary could be longer — add key achievements and skills for 3-5 solid sentences');
    } else if (len <= 500) {
      score = 15;
    } else if (len <= 800) {
      score = 12;
      suggestions.push('Summary is getting long — consider trimming to keep it concise and impactful');
    } else {
      score = 8;
      suggestions.push('Summary is too long — ATS parsers work best with 150-500 character summaries');
    }

    // Check for action verbs
    const actionVerbs = ['led', 'spearheaded', 'drove', 'optimized', 'delivered', 'architected', 'managed', 'built', 'developed', 'achieved', 'increased', 'reduced', 'implemented', 'launched', 'created', 'established', 'improved', 'designed', 'orchestrated', 'streamlined'];
    const lowerSummary = summary.toLowerCase();
    const hasActionVerb = actionVerbs.some(v => lowerSummary.includes(v));
    if (len > 0 && !hasActionVerb) {
      suggestions.push('Use strong action verbs in your summary (e.g., Led, Drove, Achieved, Optimized)');
    }

    // Check for generic filler
    const fillers = ['hard worker', 'team player', 'self-starter', 'go-getter', 'think outside the box', 'synergy'];
    const hasFiller = fillers.some(f => lowerSummary.includes(f));
    if (hasFiller) {
      score = Math.max(0, score - 2);
      suggestions.push('Remove cliché phrases like "hard worker" or "team player" — show results instead');
    }

    return {
      name: 'Professional Summary',
      score: Math.max(0, score),
      maxScore,
      passed: score >= 10,
      details: len === 0 ? 'No summary provided' : `${len} characters`,
      suggestions
    };
  }

  _checkKeywords(data) {
    let score = 0;
    const maxScore = 15;
    const suggestions = [];

    // Gather all text
    const allText = [
      data.summary || '',
      ...(data.skills || []),
      ...(data.experience || []).map(e => `${e.jobTitle} ${e.company} ${e.description}`),
      ...(data.education || []).map(e => `${e.degree} ${e.institution} ${e.description || ''}`)
    ].join(' ').toLowerCase();

    if (allText.trim().length === 0) {
      suggestions.push('Add content to your CV so ATS can match keywords from job descriptions');
      return { name: 'Keyword Density', score: 0, maxScore, passed: false, details: 'No content to analyze', suggestions };
    }

    // Count keyword matches across categories
    let totalMatches = 0;
    let matchedKeywords = [];
    Object.values(this.commonKeywords).forEach(keywords => {
      keywords.forEach(kw => {
        if (allText.includes(kw)) {
          totalMatches++;
          matchedKeywords.push(kw);
        }
      });
    });

    if (totalMatches >= 8) score = 15;
    else if (totalMatches >= 5) score = 12;
    else if (totalMatches >= 3) score = 8;
    else if (totalMatches >= 1) score = 4;
    else score = 0;

    if (totalMatches < 5) {
      suggestions.push(`Add more industry-specific keywords — currently found ${totalMatches} common ATS keywords`);
      suggestions.push('Review job descriptions you\'re targeting and include matching terms in skills and experience');
    }

    // Check quantifiable results
    const hasNumbers = /\d+[%+]|\$[\d,]+|\d+\+?\s*(years|users|clients|projects|team|people|members|reduction|increase|improvement)/i.test(allText);
    if (hasNumbers) {
      score = Math.min(15, score + 2);
    } else {
      suggestions.push('Add quantifiable achievements (e.g., "Increased revenue by 25%", "Managed team of 8")');
    }

    return {
      name: 'Keyword Density',
      score: Math.min(15, score),
      maxScore,
      passed: score >= 8,
      details: `${totalMatches} ATS keywords found${matchedKeywords.length > 0 ? ': ' + matchedKeywords.slice(0, 5).join(', ') + (matchedKeywords.length > 5 ? '...' : '') : ''}`,
      suggestions
    };
  }

  _checkExperience(experience) {
    let score = 0;
    const maxScore = 20;
    const suggestions = [];

    if (experience.length === 0) {
      suggestions.push('Add at least one work experience entry');
      return { name: 'Experience Section', score: 0, maxScore, passed: false, details: 'No experience entries', suggestions };
    }

    // Points for number of entries
    if (experience.length >= 3) score += 5;
    else if (experience.length >= 2) score += 3;
    else score += 2;

    // Check each entry
    let entriesWithDesc = 0;
    let entriesWithBullets = 0;
    let entriesWithDates = 0;

    experience.forEach(exp => {
      const desc = (exp.description || '').trim();
      if (desc.length > 0) entriesWithDesc++;
      if (desc.includes('•') || desc.includes('-') || desc.includes('*') || /\n/.test(desc)) entriesWithBullets++;
      if (exp.startDate || exp.endDate) entriesWithDates++;
    });

    // Description quality
    if (entriesWithDesc === experience.length) score += 6;
    else if (entriesWithDesc > 0) score += 3;
    else suggestions.push('Add descriptions to all experience entries — blank entries get skipped by ATS');

    // Bullet points
    if (entriesWithBullets >= Math.ceil(experience.length / 2)) score += 5;
    else if (entriesWithBullets > 0) score += 2;
    else suggestions.push('Use bullet points (•) in experience descriptions — ATS parsers handle them better than paragraphs');

    // Dates
    if (entriesWithDates === experience.length) score += 4;
    else if (entriesWithDates > 0) score += 2;
    else suggestions.push('Add start/end dates to all experience entries — ATS looks for date patterns');

    // Check for action verbs in descriptions
    const actionVerbs = ['led', 'spearheaded', 'drove', 'optimized', 'delivered', 'architected', 'managed', 'built', 'developed', 'achieved', 'increased', 'reduced', 'implemented', 'launched', 'created', 'established', 'improved', 'designed', 'orchestrated', 'streamlined'];
    const allDescs = experience.map(e => (e.description || '').toLowerCase()).join(' ');
    const hasActionVerb = actionVerbs.some(v => allDescs.includes(v));
    if (!hasActionVerb && entriesWithDesc > 0) {
      suggestions.push('Start experience bullets with strong action verbs (Led, Drove, Achieved, Optimized)');
    }

    return {
      name: 'Experience Section',
      score: Math.min(20, score),
      maxScore,
      passed: score >= 12,
      details: `${experience.length} entries, ${entriesWithDesc} with descriptions, ${entriesWithBullets} with bullet points`,
      suggestions
    };
  }

  _checkSkills(skills) {
    let score = 0;
    const maxScore = 15;
    const suggestions = [];

    if (skills.length === 0) {
      suggestions.push('Add skills — this is one of the most important sections for ATS keyword matching');
      return { name: 'Skills Section', score: 0, maxScore, passed: false, details: 'No skills listed', suggestions };
    }

    // Number of skills
    if (skills.length >= 8 && skills.length <= 15) score += 8;
    else if (skills.length >= 5) score += 6;
    else if (skills.length >= 3) score += 3;
    else score += 1;

    if (skills.length < 5) {
      suggestions.push('Add more skills — aim for 8-12 for optimal ATS matching');
    } else if (skills.length > 15) {
      score -= 2;
      suggestions.push('Consider trimming skills to your top 12 — too many can dilute relevance');
    }

    // Check for mix of hard and soft skills
    const softSkills = ['leadership', 'communication', 'problem solving', 'teamwork', 'management', 'collaboration', 'presentation', 'negotiation', 'analytical', 'creativity', 'critical thinking', 'adaptability'];
    const lowerSkills = skills.map(s => s.toLowerCase());
    const hasSoftSkill = lowerSkills.some(s => softSkills.some(ss => s.includes(ss)));
    const hasHardSkill = lowerSkills.some(s => !softSkills.some(ss => s.includes(ss)));

    if (hasSoftSkill && hasHardSkill) score += 4;
    else if (hasHardSkill) {
      score += 3;
      suggestions.push('Consider adding 1-2 soft skills (Leadership, Communication) alongside technical skills');
    } else {
      score += 2;
      suggestions.push('Add technical/hard skills — they\'re more valuable for ATS keyword matching than soft skills alone');
    }

    // Check for too-long skill names
    const longSkills = skills.filter(s => s.length > 30);
    if (longSkills.length > 0) {
      score -= 1;
      suggestions.push('Some skill names are too long — keep them concise (e.g., "React" not "React.js including Hooks and Context API")');
    }

    return {
      name: 'Skills Section',
      score: Math.max(0, Math.min(15, score)),
      maxScore,
      passed: score >= 8,
      details: `${skills.length} skills listed`,
      suggestions
    };
  }

  _checkEducation(education) {
    let score = 0;
    const maxScore = 10;
    const suggestions = [];

    if (education.length === 0) {
      score = 2;
      suggestions.push('Add your education — even if informal, ATS parsers look for this section');
    } else {
      score += 4;
      const hasDegree = education.some(e => e.degree && e.degree.trim().length > 0);
      const hasInstitution = education.some(e => e.institution && e.institution.trim().length > 0);
      const hasYear = education.some(e => e.year && e.year.trim().length > 0);

      if (hasDegree) score += 2;
      else suggestions.push('Specify degree type (e.g., Bachelor of Science, MBA)');

      if (hasInstitution) score += 2;
      else suggestions.push('Add institution name for your education entries');

      if (hasYear) score += 2;
      else suggestions.push('Add graduation year — ATS looks for date patterns in education');
    }

    return {
      name: 'Education Section',
      score: Math.min(10, score),
      maxScore,
      passed: score >= 6,
      details: `${education.length} entries`,
      suggestions
    };
  }

  _getGrade(score) {
    if (score >= 90) return 'A+';
    if (score >= 80) return 'A';
    if (score >= 75) return 'B+';
    if (score >= 65) return 'B';
    if (score >= 50) return 'C';
    if (score >= 35) return 'D';
    return 'F';
  }

  _getSummary(score) {
    if (score >= 85) return 'Excellent! Your CV is highly optimized for ATS systems.';
    if (score >= 70) return 'Good — a few tweaks will maximize your ATS compatibility.';
    if (score >= 50) return 'Fair — significant improvements needed for reliable ATS parsing.';
    if (score >= 30) return 'Needs work — many sections are missing or incomplete for ATS.';
    return 'Critical — major sections missing. Your CV may not pass ATS screening.';
  }
}

module.exports = new ATSScoreService();
